### ISSUE TITLE
Estrarre dati, dai PDF dei volumi degli invasati

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/emergenza-idrica-sicilia#13]
Da qui, i "prospetti", a partire dai più recenti https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/siti-tematici/risorse-idriche/volumi-invasati-nelle-dighe-della-sicilia

**Comment by pigreco** [comment]
@aborruso @gbvitrano ma non li hai già estratti ?
se non erro è questo file https://github.com/opendatasicilia/emergenza-idrica-sicilia/blob/main/risorse/dighe_serie_storica_melted.csv

**Comment by aborruso** [comment]
Non è colpa mia se @gbvitrano non chiude le issue
