### ISSUE TITLE
dati grezzi nelle mappe

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/emergenza-idrica-sicilia#14]
rendere disponibili i dati grezzi delle mappe sotto forma di shapefile o geojson o csv,

per esempio delle due mappe:

1. https://opendatasicilia.github.io/emergenza-idrica-sicilia/mappe/riduzione/
2. https://opendatasicilia.github.io/emergenza-idrica-sicilia/mappe/risorse/

**Comment by gbvitrano** [comment]
dove vanno caricati? una cartella risorse nel repo?

**Comment by pigreco** [comment]
> dove vanno caricati? una cartella risorse nel repo?

sì, sarebbe utilissimo

**Comment by gbvitrano** [comment]
[fatto](https://github.com/opendatasicilia/emergenza-idrica-sicilia/tree/main/risorse)
