### ISSUE TITLE
fonte dati

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/emergenza-idrica-sicilia#15]
quale è la fonte dei dati di questa mappa?
https://opendatasicilia.github.io/emergenza-idrica-sicilia/mappe/risorse/

alludo ai fiumi e agli specchi d'acqua.

**Comment by gbvitrano** [comment]
c'è scritto OS
![2024-04-07_11h34_42](https://github.com/opendatasicilia/emergenza-idrica-sicilia/assets/20488693/eeae1abb-8c79-4ad5-bde7-ea203a0aaba9)

**Comment by pigreco** [comment]
ok, grazie.

nel [PCN ](https://gn.mase.gov.it/portale/home)ci sono i WFS https://gn.mase.gov.it/portale/wfs

1. reticolo idrografico: http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/wfs/Aste_fluviali.map
2. specchi d'acqua: http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/wfs/Specchi_Acqua.map
