### ISSUE TITLE
Trovare dati di progetti PNRR nel settore idrico finanziati alla Regione Sicilia

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/emergenza-idrica-sicilia#21]
Da questo sito
https://dgdighe.mit.gov.it/categoria/_investimenti/_Programmazione/_PNRR
ho estratto i dati dei progetti PNRR finanziati alla Sicilia con le misure 4.1 e 4.2.
E ho creato questa [tabella](https://docs.google.com/spreadsheets/d/1IuorswTPt0ozcMnnliufsPd8iSfL6bijhFjrU3mkfdk/edit?usp=sharing).

Bisogna solo eliminare i progetti che sono duplicati o triplicati con lo stesso codice CUP. E tenere solo il progetto caratterizzato dal decreto più recente. Un campo è appunto quello del decreto.

Finito questo lavoro, potremmo mettere la tabella nel sito come progetti finanziati alla Regione Sicilia dal PNRR nel settore idrico.

**Comment by cirospat** [comment]
ok 
la tabella è pulita, ho tolto i duplicati

**Comment by cirospat** [comment]
ho aggiornato la pagina **Interventi prioritari**
https://opendatasicilia.github.io/emergenza-idrica-sicilia/documenti-utili/interventi-prioritari/

**Comment by aborruso** [comment]
@cirospat se per te è ok, chiudi
