### ISSUE TITLE
i dati sui volumi invasati nelle dighe della Sicilia in formato leggibile meccanicamente

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/emergenza-idrica-sicilia#24]

**Comment by aborruso** [comment]
Segnalazione fatta il [9 aprile 2024](https://docs.google.com/document/d/1P8rOBF83-dyrI4d5355-HSdSW9wTLNzQPdoMHU6RxTY/edit#heading=h.ydg8oron94ra).

**Comment by dennisangemi** [comment]
Ciao @aborruso, solo per curiosità. Su questo fronte nessun aggiornamento, vero?

**Comment by aborruso** [comment]
> Ciao @aborruso, solo per curiosità. Su questo fronte nessun aggiornamento, vero?

No, scrivo all'ufficio legale di AgID :(
