### ISSUE TITLE
Stabilire un elenco minimo di `tag` per classificare i post del blog (agggiornamenti) o bastano le `categorie`?

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/emergenza-idrica-sicilia#30]
Buongiorno
pensavo di stabilire un elenco minimo di `tag` per classificare i post del blog (aggiornamento).
Per esempio:

- atti-amministrativi
- interventi-avviati
- dissalatori
- pozzi
- ......

Oppure è sufficiente che classifichiamo i post solo nelle `categorie`?

**Comment by aborruso** [comment]
Chiudo, perché ho aperto questa https://github.com/opendatasicilia/emergenza-idrica-sicilia/issues/31

Ciro, nel frattempo però procediamo. Nei prossimi giorni i tag saranno attivati.
