### ISSUE TITLE
video su emergenza idrica sicilia

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/emergenza-idrica-sicilia#36]
https://www.google.com/search?sca_esv=0fe37503bf42aa9a&rlz=1C1CHBF_itIT970IT970&tbm=vid&sxsrf=ACQVn0-ewI_nf7RVoH1wuBoe5LlzJR5aHg:1712845464832&q=emergenza+idrica+in+sicilia&sa=X&ved=2ahUKEwjrzvHLrrqFAxUhgf0HHUPfD6QQ8ccDegQIPRAF&biw=1920&bih=919

**Comment by cirospat** [comment]
sono video di testate giornalistiche. Che possono essere politicamente di parte opposta all'amministrazione regionale, il che screditerebbe il nostro lavoro, secondo me.
Non lo so.
Se fossero video della Regione o degli enti preposti alla gestione dell'emergenza, sarebbe più coerente con lo spirito del sito.

**Comment by pigreco** [comment]
se vedi questo pericolo possiamo chiudere issue
