### ISSUE TITLE
creare datapackage per i dati volumi invasati dighe, estratti da questi PDF

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/emergenza-idrica-sicilia#38]

**Comment by aborruso** [comment]
Due i CSV coinvolti, presenti [qui](https://github.com/opendatasicilia/emergenza-idrica-sicilia/tree/main/risorse):

- dighe_serie_storica_melted.csv
- dighe_anagrafica.csv

@dennisangemi se ne è occupato @gbvitrano di estrarli dalle decine di PDF.

Nel creare il datapackage, se serve cambiare qualcosa dei dati, fallo pure. Magari per ora in una cartella nuova, così poi mappiamo con Gianni Eventuali dipendenze.

**Comment by dennisangemi** [comment]
Sera! Stavo cominciando a generare un datapackage ma c'è questa cosa che non mi convince 

https://github.com/opendatasicilia/emergenza-idrica-sicilia/blob/9db555dbfa3da641b895881fb61d1874fd7b6016/risorse/README.md?plain=1#L24

@gbvitrano sicuro che l'url al pdf sia corretto?

**Comment by gbvitrano** [comment]
i link di tabelle ed i grafici degli invasi sono raccolti [[qui](https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/siti-tematici/risorse-idriche/volumi-invasati-nelle-dighe-della-sicilia) ogni anno dal 2011 ha una sua pagina

**Comment by dennisangemi** [comment]
Ho rimosso gli header ripetuti all'interno di `dighe_serie_storica_melted.csv` che sono nati durante la concatenzione con 

```sh
grep -v "cod,Diga,Variable,Value" dighe_serie_storica_melted.csv
```

**Comment by dennisangemi** [comment]
@gbvitrano grazie! Puoi correggere anche questo link per favore?

https://github.com/opendatasicilia/emergenza-idrica-sicilia/blob/e39d6bbdb8edc6cc72337f967dd8bb79d005f6e2/risorse/README.md?plain=1#L5

**Comment by dennisangemi** [comment]
Per ora i file sono validi ma bisogna ancora arricchire il datapackage

![image](https://github.com/opendatasicilia/emergenza-idrica-sicilia/assets/77018886/0b9b099a-2204-4a31-a88c-bf02bf5ef952)

**Comment by dennisangemi** [comment]
> @gbvitrano grazie! Puoi correggere anche questo link per favore?
> 
> https://github.com/opendatasicilia/emergenza-idrica-sicilia/blob/e39d6bbdb8edc6cc72337f967dd8bb79d005f6e2/risorse/README.md?plain=1#L5

ping @gbvitrano

**Comment by gbvitrano** [comment]
Se non ricordo male l'ho modificato quando ci siamo accorti dell'errore

**Comment by dennisangemi** [comment]
@gbvitrano questa è un'altra linea. È un link che si riferisce al file dell'anagrafica

**Comment by gbvitrano** [comment]
> @gbvitrano questa è un'altra linea. È un link che si riferisce al file dell'anagrafica

il file anagrafica non ha un link di riferimento, è una cosa che mi sono inventato io. Nei pdf delle dighe non sono sempre riportate tutte le dighe

**Comment by gbvitrano** [comment]
cambiato la dicitura....

## dighe_anagrafica

È un file csv è stata costruito  *ad hoc*  per organizzare i dati scrapati dai [PDF](https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/siti-tematici/risorse-idriche/volumi-invasati-nelle-dighe-della-sicilia) dal 2010 al 2024

**Comment by dennisangemi** [comment]
D'accordo @gbvitrano, grazie! Non avevo capito che l'avessi costruito appositamente, pensavo fosse estratto. Correggerò anche il datapackage

Colgo l'occasione per chiederti se posso operare le seguenti modifiche sull'anagrafica:
1. Eliminare la colonna con lat e long concatenati 
2. Aggiungere il codice istat del comune

**Comment by gbvitrano** [comment]
Codice istat si, se togli le coordinate come si geolocalizzano le dighe? 
Le coordinate sono riferite alle dighe e non al Comune\territorio

**Comment by gbvitrano** [comment]
mi correggo la colonna coordinate si può anche eliminare :-) anche se potrebbe essere utile in alcuni software che accettano i valori di lat e long concatenati

**Comment by dennisangemi** [comment]
D'accordo @gbvitrano, allora visto che mi hai dato la benedizione, la elimino e faccio una PR asap. Aggiorno il datapackage e poi possiamo anche chiudere questa issue

**Comment by dennisangemi** [comment]
Ciao @gbvitrano, torno su questa issue dopo un po' di tempo. Ho alcune idee, dimmi tu come le reputi:

1. Rinominerei `dighe_anagrafica` in `sicilia_dighe_anagrafica` dato che nella stessa cartella sono presenti alcuni dati che si riferiscono alle dighe italiane 
2. Rinominerei `dighe_serie_storica_melted` in `sicilia_dighe_volumi` dato che questo file contiene solo i valori dei volumi linkati agli id della diga (bellissimo!)
3. Rinominerei `grandi_dighe_italiane` in `italia_grandi_dighe` in modo tale da indicare la dimensione territoriale a cui si riferiscono i dati del file nella prima parte del filename (per questioni di coerenza)

Queste modifiche immagino intaccherebbero le mappe e bisognerebbe aggiornare gli url che puntano ai dati. Dici che è una cosa fattibile?
