### ISSUE TITLE
Estrarre opere da II Relazione alla cabina di regia

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/emergenza-idrica-sicilia#4]
La tabella di [questo PDF](https://opendatasicilia.github.io/emergenza-idrica-sicilia/documenti-utili/relazione_cabina-regia_commissario-straordinario-nazionale_interventi-scarsita-idrica.pdf), pagina 116 e 117: i soli dati della Sicilia.

**Comment by aborruso** [comment]
[relazione_cabina-regia_commissario-straordinario-nazionale_interventi-scarsita-idrica_interventi.ods](https://github.com/opendatasicilia/emergenza-idrica-sicilia/files/14902713/relazione_cabina-regia_commissario-straordinario-nazionale_interventi-scarsita-idrica_interventi.ods)

**Comment by cirospat** [comment]
estratte
e messe qui
https://opendatasicilia.github.io/emergenza-idrica-sicilia/documenti-utili/interventi-2-relazione-cabinaregia-nazionale/
