### ISSUE TITLE
Tabella erogazione idrica Regalbuto: inserire metadati in testo introduttivo

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/emergenza-idrica-sicilia#45]
Caro @dennisangemi, inserisci nel testo un link al (ai) file che hai usato per estrarre i dati che alimentano la tabella?

![image](https://github.com/user-attachments/assets/9e8e1f2d-1525-40f1-b6ff-44d581e01feb)

**Comment by aborruso** [comment]
@gbvitrano metterei tutto su [Felt](https://felt.com/), che è molto più light di tableau e più adatto.

**Comment by dennisangemi** [comment]
> @dennisangemi la tabella aggiornata con le nuove maglie il comune l'ha pubblicata?

@gbvitrano il gestore aveva dimenticato di allegarla alla comunicazione effettuata al protocollo. Immagino l'abbiano richiesta. Ti aggiorno domani

**Comment by gbvitrano** [comment]
> 

Vie Risolte... ho chiesto a mio cugino, cmq sono da verificare, visto che sei del luogo

https://public.tableau.com/views/Regalbuto/Turno_erogazione_idrica_Regalbuto?:language=it-IT&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link

**Comment by dennisangemi** [comment]
Ciao @aborruso, chiudo questa issue perchè ho aggiunto i link a cui facevi riferimento

![image](https://github.com/user-attachments/assets/0dc82f77-a2ab-4489-96ff-ced488bfa985)

Grazie!

**Comment by aborruso** [comment]
Grazie
