### ISSUE TITLE
[volumi invasati] verificare dati di giugno 2024

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/emergenza-idrica-sicilia#53]
Picco anomalo per lentini, poma, garcia (ma controllare tutte le dighe)

![image](https://github.com/user-attachments/assets/6367511c-ae87-4a06-be99-337068afb373)

(viz non ancora pubblica)

**Comment by pigreco** [comment]
da qui AEGIS (livello ifdrometrico - giugno 2024) https://www.protezionecivilesicilia.it:8443/aegis/map/map2d

![image](https://github.com/user-attachments/assets/0203ef95-6527-4334-8d9a-ad15ea0a02e7)

**Comment by aborruso** [comment]
@dennisangemi che fa le soprese ❣️

**Comment by dennisangemi** [comment]
Risolto! 

![image](https://github.com/user-attachments/assets/ee56139a-65d4-423a-baf5-2ba89ea9e199)

Qui una preview della dashboard (ancora wip) https://lookerstudio.google.com/reporting/241228ac-70d4-4861-88c7-a9058ab28a11

**Comment by dennisangemi** [comment]
Grazie @pigreco!

**Comment by aborruso** [comment]
> Risolto!

In che senso? C'era un errore nei dati?

**Comment by dennisangemi** [comment]
> In che senso? C'era un errore nei dati?

@aborruso esatto, qualcosa durante l'estrazione dei dati di giugno era andata sorta. C'erano dati errati che ho corretto sulla base del pdf della regione https://www.regione.sicilia.it/sites/default/files/2024-06/0__2024.06.01_A_Tabella_volumi_invasi.pdf

Per estrarre i dati di giugno ho usato

```sh
 curl -s https://raw.githubusercontent.com/opendatasicilia/emergenza-idrica-sicilia/refs/heads/main/risorse/sicilia_dighe_anagrafica.csv | llm -t volumi_dighe -a pdf/Tabelle/volumi_2024-06.pdf > 2024-06.csv
```

con template:
```yaml
system: Il tuo compito è quello di estrarre dati da un pdf allegato e di incrociarli con i dati di un'anagrafica csv passata come prompt. Dalla tabella pdf, individua la data di rilevazione e poi estrai tutti i dati della colonna diga (chiamala 'diga_pdf') e quelli della colonna relativa al volume registrato nel mese più recente. Arricchisci la tabella aggiungendo una colonna chiamata 'data' che abbia in ogni riga la data della rilevazione più recente a cui si riferiscono i dati nel formato yyyy-mm-dd. Dal CSV, estrai la colonna 'diga' che chiamerai 'diga_anagrafica' popolata con il nome corretto (da includere esattamente nell'output). Confronta le colonne 'diga_pdf' e 'diga_anagrafica' per fare in modo di arricchire il dataset e assegnare a ogni diga il corrispondente codice identificativo presente nella colonna 'cod' del csv. Attenzione alla diga ogliastro e don sturzo che sono la stessa cosa. In ultimo, cestina la colonna 'diga_pdf' e  nell'output includi i valori di 'diga_anagrafica' sotto il nome di 'diga'. Attenzione ad attribuire correttamente il codice al nome della diga secondo l'anagrafica csv. Se l'anagrafica csv contiene più dighe della tabella pdf, l'output deve contenere solo ed esclusivamente le dighe presenti nel file pdf. Se nell'anagrafica ci sono più dighe del pdf, il volume non deve essere 0 ma deve essere vuoto. L'output deve avere questa struttura 'cod,diga,data,volume'. Tieni presente che i valori di 'diga' devono essere esattamente coincidenti con quelli di 'diga_anagrafica'. I separatori di decimali dei volumi devono essere i punti e non le virgole. L'output non deve contenere i backtips all'inizio e alla fine ma solo il contenuto del file csv a cominciare dagli header.
```

e `gemini-1.5-pro-latest` come modello.

Non sarà il più bel system prompt di sempre... però funziona (l'ho dovuto modificare un paio di volte)

**Comment by aborruso** [comment]
Sarà bello raccontarlo!!

**Comment by aborruso** [comment]
C'è da aggiungere di rimuovere le righe vuote.
Ma è bellissimo

![image](https://github.com/user-attachments/assets/7a4ad3dd-a0a4-4ad8-a158-744b92d6415a)

**Comment by dennisangemi** [comment]
Hai ragione @aborruso! In realtà per lo scopo di questo repo c'è anche da modificare la data in dd/mm/yyyy perchè per qualche ragione dall'inizio di questo repo è stato utilizzato questo formato.

Anche se io convertirei le date del repo da dd/mm/yyyy a yyyy-mm-dd... Magari apro issue dedicata e ne parliamo
