### ISSUE TITLE
[workflows] run failed

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/emergenza-idrica-sicilia#54]
Buongiorno @aborruso, @gbvitrano, @cirospat, @pigreco,

Ho combinato danno io o c'è un bug?

https://github.com/opendatasicilia/emergenza-idrica-sicilia/actions

![image](https://github.com/user-attachments/assets/dfc3f71f-37b0-41e5-8cdc-0ccf175cef39)

i miei commit riguardano solo la directory `risorse` e credo di non aver toccato `docs`.

Ci date un'occhiata appena potete per favore? Grazie ;)

**Comment by aborruso** [comment]
No, non dipende da te.

Tu al momento stai lavorando soltanto su dati, o ti è necessario anche aggiornare contenuti visibili nel sito?

**Comment by dennisangemi** [comment]
> Tu al momento stai lavorando soltanto su dati, o ti è necessario anche aggiornare contenuti visibili nel sito?

@aborruso solo dati, niente sito

> No, non dipende da te.

D'accordo, grazie!

**Comment by dennisangemi** [comment]
Bisogna modificare le date del blog in modo tale che abbiano tutte lo stesso formato. Faccio io

**Comment by aborruso** [comment]
Grazie Dennis!!

**Comment by gbvitrano** [comment]
![2024-11-23_08h32_16](https://github.com/user-attachments/assets/4ec9e7f3-3016-47a9-8667-01130ece3d88)
è un bug di Martino c'è una issue aperta https://github.com/squidfunk/mkdocs-material/issues/7725
