### ISSUE TITLE
[volumi_invasati] automatizzare check di nuovi pdf ed estrazione dati

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/emergenza-idrica-sicilia#60]
Ho preparato una bozza di scraper + estrattore che usa scrape-cli di @aborruso e llm, è da perfezionare ma funzionicchia

## Codice
Lo trovate in [`scripts/scrape_convert.sh`](https://github.com/opendatasicilia/emergenza-idrica-sicilia/blob/main/scripts/scrape_convert.sh)

## Configurazione template `volumi_dighe` di `llm'

```
system: Il tuo compito è quello di estrarre dati da un pdf allegato e di incrociarli con i dati di un'anagrafica csv passata come prompt. Dalla tabella pdf, individua la data di rilevazione e poi estrai tutti i dati della colonna diga (chiamala 'diga_pdf') e quelli della colonna relativa al volume registrato nel mese più recente. Arricchisci la tabella aggiungendo una colonna chiamata 'data' che abbia in ogni riga la data della rilevazione più recente a cui si riferiscono i dati nel formato yyyy-mm-dd. Dal CSV, estrai la colonna 'diga' che chiamerai 'diga_anagrafica' popolata con il nome corretto (da includere esattamente nell'output). Confronta le colonne 'diga_pdf' e 'diga_anagrafica' per fare in modo di arricchire il dataset e assegnare a ogni diga il corrispondente codice identificativo presente nella colonna 'cod' del csv. Attenzione alla diga ogliastro e don sturzo che sono la stessa cosa. In ultimo, cestina la colonna 'diga_pdf' e  nell'output includi i valori di 'diga_anagrafica' sotto il nome di 'diga'. Attenzione ad attribuire correttamente il codice al nome della diga secondo l'anagrafica csv. Se l'anagrafica csv contiene più dighe della tabella pdf, l'output deve contenere solo ed esclusivamente le dighe presenti nel file pdf. Se nell'anagrafica ci sono più dighe del pdf, il volume non deve essere 0 ma deve essere vuoto. L'output deve avere questa struttura 'cod,diga,data,volume' e non deve avere righe vuote finali. Tieni presente che i valori di 'diga' devono essere esattamente coincidenti con quelli di 'diga_anagrafica'. I separatori di decimali dei volumi devono essere i punti e non le virgole. L'output non deve contenere i backtips all'inizio e alla fine ma solo il contenuto del file csv a cominciare dagli header L'output non deve contenere righe vuote alla fine. Se l'output csv contiene righe finali senza valori, rimuovile.
```

## Esempio di output
```
/sites/default/files/2024-11/1__2024.11.01_A_Tabella_volumi_invasi_0.pdf è un nuovo pdf
il nuovo nome è volumi_2024-11.pdf
ho scaricato volumi_2024-11.pdf
volumi_2024-11.pdf è un pdf di volumi quindi provo a convertirlo in csv
ho convertito volumi_2024-11.pdf in volumi_2024-11.pdf.csv
/sites/default/files/2024-11/0__2024.11.01_C_Grafici_volumi_invasi.pdf è un nuovo pdf
il nuovo nome è grafici_2024-11.pdf
ho scaricato grafici_2024-11.pdf
/sites/default/files/2024-12/1__2024.12.01_A_Tabella_volumi_invasi.pdf è un nuovo pdf
il nuovo nome è volumi_2024-12.pdf
ho scaricato volumi_2024-12.pdf
volumi_2024-12.pdf è un pdf di volumi quindi provo a convertirlo in csv
ho convertito volumi_2024-12.pdf in volumi_2024-12.pdf.csv
/sites/default/files/2024-12/0__2024.12.01_C_Grafici_volumi_invasi.pdf è un nuovo pdf
il nuovo nome è grafici_2024-12.pdf
ho scaricato grafici_2024-12.pdf
Ci sono 4 nuovi pdf
Fine, bye!
```

## To do
- [x] fixare la posizione dei file di output
- [x] fixare il nome file del csv per non avere `.pdf.csv` ma solo `.csv`
- [x] esplicitare system prompt per non dover configurare il template
- [x] settare api key https://github.com/opendatasicilia/emergenza-idrica-sicilia/issues/61
- [x] sostituire l'import dell'anagrafica tramite curl con semplicemente `< risorse/sicilia_dighe_anagrafica.csv  mlr --csv cut -f cod,diga` (testare!) oppure con `cat risorse/sicilia_dighe_anagrafica.csv`
- [ ] #65

## Note
ci sono alcune scelte poco solide tipo 

```sh
# obtain current year
year=$(date +"%Y")

# build page name to enter
page_name="Anno $year"
```

che sfruttano l'assunto che in questa pagina https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/siti-tematici/risorse-idriche/volumi-invasati-nelle-dighe-della-sicilia ci sia sempre scritto "Anno YYYY" (con YYYY anno corrente). Non so come si possa rendere più solido. Forse usare llm che va a cercare qual è il link che rimanda alla pagina con l'anno più recente?

## Perfezionamento
ci lavoro un po' a natale ma se qualcuno di voi ha idee migliori e riesce a lavorarci prima, felice di avervi fornito una base su cui costruire sopra altre cose!

## Grazie
come sempre a @aborruso non solo per `scrape-cli` ma anche per avermi fatto scoprire `llm`

**Comment by aborruso** [comment]
Grazie mille

**Comment by aborruso** [comment]
@dennisangemi io do una mano sicuro, ma tra natale e capodanno

**Comment by aborruso** [comment]
@dennisangemi con che modello llm hai testato?

**Comment by aborruso** [comment]
> Non so come si possa rendere più solido. Forse usare llm che va a cercare qual è il link che rimanda alla pagina con l'anno più recente?

L'interpretazione via un LLM potrebbe essere la migliore. Ma per il momento andrei sereno e light. Tanto il prossimo sta entrando a breve.

Potresti interrogare cambiando approccio, ovvero prendendo sempre l'ultimo

```
#it-block-field-blocknodegeneric-pagefield-p-body li:last-of-type a:last-of-type
```

che in questo caso ti darebbe

```json
{
  "a": {
    "@href": "https://www.regione.sicilia.it/istituzioni/regione/strutture-regionali/presidenza-regione/autorita-bacino-distretto-idrografico-sicilia/volumi-invasi-anno-2024",
    "#text": "Anno 2024"
  }
}
```

**Comment by dennisangemi** [comment]
Grazie mille @aborruso 

> con che modello llm hai testato?

`gemini-1.5-pro-latest` ma se pensi che ce ne siano di altri online in grado di supportare `-a` di `llm` lemme know pls

> Potresti interrogare cambiando approccio, ovvero prendendo sempre l'ultimo

Figata! Grazie, lo implemento

**Comment by dennisangemi** [comment]
Commit https://github.com/opendatasicilia/emergenza-idrica-sicilia/commit/4d5d73ee1b32c145dba301642ef421c64968a520
