### ISSUE TITLE
[autorizzazione repo] abilitare settings

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/emergenza-idrica-sicilia#61]
Ciao @aborruso, vorrei settare i secrets per l'api di gemini (o di altri servizi se credi siano migliori) ma non riesco a vedere il pannello `settings` del repo. Mi puoi abilitare per favore? grazie!

**Comment by aborruso** [comment]
Ciao @dennisangemi lo faccio il prima possibile. 

Ma probabilmente sarà sabato.

Scusa la lentezza

**Comment by dennisangemi** [comment]
Non ti preoccupare, nessun problema e grazie!

Il Gio 19 Dic 2024, 13:58 Andrea Borruso ***@***.***> ha
scritto:

**Comment by aborruso** [comment]
Ciao @dennisangemi ti ho reso mantainer. Mi dici se ora riesci?

**Comment by dennisangemi** [comment]
Grazie mille @aborruso, confermo. Ho aggiunto la mia key. Chiudo e grazie!

**Comment by aborruso** [comment]
Grazie a te
