### ISSUE TITLE
[dati] aggiungere validazione frictionless action

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/emergenza-idrica-sicilia#64]

**Comment by dennisangemi** [comment]
https://github.com/opendatasicilia/emergenza-idrica-sicilia/commit/087a75e21b5948c2a896c3f2f29431e5d9a6f0cd

**Comment by dennisangemi** [comment]
adesso se la validazione frictionless fallisce, il bot non committa i nuovi dati estratti tramite ai

esempio: https://github.com/opendatasicilia/emergenza-idrica-sicilia/actions/runs/12510756553/job/34901927428

**Comment by dennisangemi** [comment]
Ho preferito installare manualmente frictionless e verificare l'esito della validazione per abbattere i tempi di esecuzione.

Il setup del repository di frictionless tramite action ufficiale si prende un minuto intero...

Vd https://github.com/opendatasicilia/emergenza-idrica-sicilia/actions/runs/12509962874/job/34900117137

**Comment by aborruso** [comment]
> Ho preferito installare manualmente frictionless e verificare l'esito della validazione per abbattere i tempi di esecuzione.

Ciao caro. In che senso hai preferito installare manualmente? 
Come lo installavi prima?

Stai facendo proprio un bel lavoro

**Comment by dennisangemi** [comment]
Ciao @aborruso, grazie! Per modalità "non manuale" intendo il frictionless repository https://repository.frictionlessdata.io/docs/getting-started.html

**Comment by aborruso** [comment]
> Ciao @aborruso, grazie! Per modalità "non manuale" intendo il frictionless repository [repository.frictionlessdata.io/docs/getting-started.html](https://repository.frictionlessdata.io/docs/getting-started.html)

Sono fuori forma: appena puoi, mi scrivi come installavi prima (quando durava tanto) e come installi ora (che dura meno)?

Grazie e porta pazienza

**Comment by dennisangemi** [comment]
@aborruso non preoccuparti, probabilmente io non uso i termini corretti e rendo più difficile la storia.

# Prima
Tra i [progetti di frictionless](https://frictionlessdata.io/projects/) c'è [**Frictionless Repository**](https://repository.frictionlessdata.io/): _Github Action allowing you to validate tabular data on every commit to your repository._

![image](https://github.com/user-attachments/assets/3ce1c638-69ec-4bf0-9f3a-e024c3d9a113)

È una github action che si [configura in questo modo](https://repository.frictionlessdata.io/docs/getting-started.html) e ci mette circa un minuto SOLO per predisporre l'ambiente (vd. https://github.com/opendatasicilia/emergenza-idrica-sicilia/actions/runs/12509962874/job/34900117137#step:2:1)

![image](https://github.com/user-attachments/assets/8a7efb4b-6855-49fc-b985-07c10bed26fa)

La cosa carina di questo metodo è che offre la possibilità di produrre uno status badge che se cliccato rimanda a un report interattivo html con gli errori riscontrati (a me il report non funziona quasi mai, credo ci sia qualche bug lato frictionless ma non ne sono sicuro)

Esempio di badge nel [repo di anpr](https://github.com/italia/anpr-opendata) 

[![image](https://github.com/user-attachments/assets/d6044347-ea2c-4f88-951e-9ce47cb5f209)](https://github.com/italia/anpr-opendata)

L'ultimo run di questa action per anpr è [questo ](https://github.com/italia/anpr-opendata/actions/runs/12512723849/job/34906405355#step:4:9) in cui viene indicato un url al report interattivo.

Il report interattivo dovrebbe essere [questo ](https://repository.frictionlessdata.io/pages/dashboard.html?user=italia&repo=anpr-opendata&flow=frictionless)ma torna errore e non viene visualizzato.

Usavo questo metodo in https://github.com/opendatasicilia/covid-open-report-sicilia (ad esempio)

## In sintesti

### Pro
- si implementa in solo due righe di github workflows
- produce status badge
- produce (in teoria) report interattivo

### Contro
- la predisposizione dell'ambiente è lenta (1 min)
- il report interattivo pare non funzioni sempre

# Ora
Uso `uv pip install frictionless` (ma andrebbe bene anche `pip install frictionless` e faccio il run della validazione con `frictionless validate datapackage.yaml --yaml`. Se la validazione fallisce, non faccio commit dei nuovi dati. Esempio qui: https://github.com/opendatasicilia/emergenza-idrica-sicilia/actions/runs/12510756553/job/34901927428
